services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USER}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - app_network
    depends_on:
      - mongodb

  cassandra:
    image: cassandra
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "${CASSANDRA_USER}", "-p", "${CASSANDRA_PASSWORD}", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - app_network

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # --- APLICAÇÃO ---
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcc_api_server
    env_file:
      - .env
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    networks:
      - app_network
    depends_on:
      mongodb:
        condition: service_started
      cassandra:
        condition: service_healthy
      neo4j:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tcc_streamlit_app
    command: streamlit run src/streamlit_app/app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./src:/app/src
    ports:
      - "8501:8501"
    networks:
      - app_network
    depends_on:
      - api

networks:
  app_network:

volumes:
  mongodb_data:
  cassandra_data:
  neo4j_data:
  redis_data: